services:
  backend:
    build: ./backend/ecommerce
    ports:
      - 8080:8080
    depends_on:
      postgresqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123qwe
      - SPRING_JPA.HIBERNATE.DDL_AUTO=create
  postgresqldb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend/e-commerce-app
    ports:
      - 3000:3000
    depends_on:
      - backend
  
